<a href="https://colab.research.google.com/github/SergeiSa/Extra-math-for-high-school/blob/main/ColabNotebooks/Vectors_Matrices_Norms_LinSystems_Determinants.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Solving equations

Let us solve:

\begin{equation}
\begin{cases}
x_1   + 2 x_2 = 10 \\
2 x_1 + 2 x_2 = 0 
\end{cases}
\end{equation}

This is the same as

\begin{equation}
\begin{bmatrix}
1   & 2  \\
2   & 2  
\end{bmatrix}
\begin{bmatrix}
x_1  \\
x_2 
\end{bmatrix}
=
\begin{bmatrix}
10  \\
0 
\end{bmatrix}
\end{equation}

General form for this kind of problem is:


\begin{equation}
\mathbf{A} \mathbf{x} = \mathbf{b}
\end{equation}

In this course we will solve it with $\texttt{x = np.linalg.solve(A, b)}$ functionality of numpy. 

In [ ]:
import numpy as np

A = np.array([[1, 2], [2, 2]])
b = np.array([10, 0])

x = np.linalg.solve(A, b)

print("solution:")
print(x)
print("residual:")
print(A@x - b)

solution:
[-10.  10.]
residual:
[0. 0.]


Let us do it by hand. $2x_1 + 2x_2 = 0$, hence $x_1 = -x_2$, and therefore $x_1 + 2x_2 = 10$ becomes $-x_2 + 2x_2 = 10$, meaning that $x_2 = 10$ and finally $x_1 = -10$, QED.

When we want to note the dimension of a vector, we use the following notation:

\begin{equation}
\mathbf{b} \in \mathbb{R}^n
\end{equation}

where $\mathbb{R}$ means space of real numbers and $n$ is the dimensions.

For matrices it is similar:

\begin{equation}
\mathbf{A} \in \mathbb{R}^{n, n}
\end{equation}

Why use this strange $\mathbb{R}$? Because later you might see something like $\mathbf{b} \in \mathbb{C}^n$, meaning it is a complex vector, or $\mathbf{b} \in \mathbb{N}^n$ meaning it is a vector of integers. 

# Other dimensions

Dimensions do not matter, we can deal with equations with 2, 3 and more variables the same way:

\begin{equation}
\begin{cases}
x_1   - 4 x_2 + 5 x_3= 1 \\
3 x_1 +   x_2 - 2 x_3= 1 \\ 
2 x_1 - 6 x_2 - 9 x_3= -2 
\end{cases}
\end{equation}

This is the same as

\begin{equation}
\begin{bmatrix}
1   & -4 &  5  \\
3   &  1 & -2  \\  
2   & -6 & -9   
\end{bmatrix}
\begin{bmatrix}
x_1  \\
x_2  \\
x_3 
\end{bmatrix}
=
\begin{bmatrix}
1  \\
1   \\
-2 
\end{bmatrix}
\end{equation}

Again, it is $\mathbf{A} \mathbf{x} = \mathbf{b}$ and we solve it with $\texttt{x = np.linalg.solve(A, b)}$. 

In [ ]:
A = np.array([[1, -4, 5], [3, 1, -2], [2, -6, -9]])
b = np.array([1, 1, -2])

x = np.linalg.solve(A, b)

print("solution:")
print(x)
print("residual:")
print(A@x - b)

solution:
[0.43661972 0.14084507 0.22535211]
residual:
[-2.22044605e-16 -1.11022302e-16  0.00000000e+00]


# Solving degenerate equations
## Too many variables

Let us solve a degenerate system of equations:

\begin{equation}
x_1   + 2 x_2 = 10
\end{equation}

This is the same as

\begin{equation}
\begin{bmatrix}
1   & 2
\end{bmatrix}
\begin{bmatrix}
x_1  \\
x_2 
\end{bmatrix}
=
10
\end{equation}

General form for this kind of problem is still:

\begin{equation}
\mathbf{A} \mathbf{x} = \mathbf{b}
\end{equation}

We can solve it with $\texttt{x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)}$ fucntionality of numpy. 

In [ ]:
A = np.array([[1, 2]])
b = np.array([10])

x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)

print("solution:")
print(x)
print("residual:")
print(A@x - b)

solution:
[2. 4.]
residual:
[0.]


## Too many equations

Let us solve a degenerate system of equations:

\begin{equation}
\begin{cases}
  x_1   + 2 x_2 = 2 \\
3 x_1   - 5 x_2 = 0  \\
2 x_1   - 4 x_2 = 5
\end{cases}
\end{equation}

This is the same as

\begin{equation}
\begin{bmatrix}
1   &  2 \\
3   & -5 \\ 
2   & -4
\end{bmatrix}
\begin{bmatrix}
x_1  \\
x_2 
\end{bmatrix}
=
\begin{bmatrix}
2 \\ 0 \\ 5
\end{bmatrix}
\end{equation}

General form for this kind of problem is still:

\begin{equation}
\mathbf{A} \mathbf{x} = \mathbf{b}
\end{equation}

We can solve it with $\texttt{x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)}$ fucntionality of numpy. 



In [ ]:
A = np.array([[1, 2], [3, -5], [2, -4]])
b = np.array([[2], [0], [5]])

x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)

print("solution:")
print(x)
print("residual:")
print(A@x - b)

solution:
[[1.07936508]
 [0.14814815]]
residual:
[[-0.62433862]
 [ 2.4973545 ]
 [-3.43386243]]


Note that residual is not zero!

## Degenerate square system

The following system i ssquare (same number of variable and equations) but you still can not solve it normally:

\begin{equation}
\begin{cases}
  x_1   - 2 x_2 = 0 \\
3 x_1   - 6 x_2 = 2 
\end{cases}
\end{equation}

This is the same as

\begin{equation}
\begin{bmatrix}
1   & -2 \\
3   & -6 
\end{bmatrix}
\begin{bmatrix}
x_1  \\
x_2 
\end{bmatrix}
=
\begin{bmatrix}
0 \\ 2
\end{bmatrix}
\end{equation}

And it does not have a zero-residual solution.


In [ ]:
A = np.array([[1, -2], [3, -6]])
b = np.array([[0], [2]])

x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)

print("solution:")
print(x)
print("residual:")
print(A@x - b)

solution:
[[ 0.12]
 [-0.24]]
residual:
[[ 0.6]
 [-0.2]]


## How do you tell if a system can be solved?

The test is - to find if the matrix **determinant** is not zero.

For 2 by 2 matrices, the determinant is found as follows:

\begin{equation}
\mathbf A =
\begin{bmatrix}
a   & b  \\
c   & d  
\end{bmatrix}
\end{equation}

\begin{equation}
\text{det} (\mathbf A) =
ad - bc
\end{equation}

For anything other than 2 by 2 we find determinant as $\texttt{d = np.linalg.det(A)}$ fucntionality of numpy. 

In [ ]:
A = np.array([[1, -2], [3, -6]])
d = np.linalg.det(A)

print("determinant, matrix 1:")
print(d)

A = np.array([[1, 1], [3, -6]])
d = np.linalg.det(A)

print("determinant, matrix 2:")
print(d)

determinant, matrix 1:
0.0
determinant, matrix 2:
-9.000000000000002


If a matrix has 0 determinant we call it **degenerate**. If the matrix has non-zero determinant, we call it **full-rank**.

Some of the rules for degenerate matrices and determinants:


*   If a matrix has linearly dependant columns or rows it would have 0 determinant.
*   Only square matrices have a determinant.



# Linear combination

Given a few vectors $\mathbf v_1$, $\mathbf v_2$, ..., $\mathbf v_n \in \mathbb{R}^n$, their linear combination is defined as:

\begin{equation}
\mathbf w = \alpha_1 \mathbf v_1 + \alpha_2 \mathbf v_2 + ... + \alpha_n \mathbf v_n
\end{equation}

where $\alpha_i \in \mathbb{R}$ are linear coefficients.

### Example

Given $\mathbf v_1$ and $\mathbf v_2$:

\begin{equation}
\mathbf v_1 = 
\begin{bmatrix} 
1 \\ 3
\end{bmatrix}, \ \ 
\mathbf v_2 = 
\begin{bmatrix} 
0 \\ 1
\end{bmatrix}
\end{equation}

Then examples of their linear combinations are:

\begin{equation}
\mathbf w = 2 \mathbf v_1 - \mathbf v_2 = 
2
\begin{bmatrix} 
1 \\ 3
\end{bmatrix}
-
\begin{bmatrix} 
0 \\ 1
\end{bmatrix}
=
\begin{bmatrix} 
2 \\ 5
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf w = - 3\mathbf v_1 + 2\mathbf v_2 = 
-3
\begin{bmatrix} 
1 \\ 3
\end{bmatrix}
+2
\begin{bmatrix} 
0 \\ 1
\end{bmatrix}
=
\begin{bmatrix} 
-3 \\ -7
\end{bmatrix}
\end{equation}


\begin{equation}
\mathbf w = 5\mathbf v_2 = 
5
\begin{bmatrix} 
0 \\ 1
\end{bmatrix}
=
\begin{bmatrix} 
0 \\ 5
\end{bmatrix}
\end{equation}

If a set of vectors contain none that is a linear combination of the others - we call them **linearly independant**.

# Linear combination and degenerate matrix

If one of your matrix's columns is a linear combination of teh other - it will be degenerate. Lets look for an example. Consider teh matrix:

\begin{equation}
\mathbf A =
\begin{bmatrix}
a_{11}   & a_{12}   \\
a_{21}   & a_{22}   
\end{bmatrix}
\end{equation}

Its columns are $\mathbf a_1$ and $\mathbf a_2$:

\begin{equation}
\mathbf a_1 =
\begin{bmatrix}
a_{11}      \\
a_{21}     
\end{bmatrix}, \ \ 
\mathbf a_2 =
\begin{bmatrix}
a_{21}      \\
a_{22}     
\end{bmatrix}
\end{equation}

If, for instance, $\mathbf a_2 = 2 \mathbf a_1$, the matrix $\mathbf A$ will be degenerate.

### Example

\begin{equation}
\mathbf a_1 =
\begin{bmatrix}
2      \\
-3     
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf a_2 = -\mathbf a_1 =
\begin{bmatrix}
-2      \\
3     
\end{bmatrix}
\end{equation}

Then matrix $\mathbf A =
\begin{bmatrix}
2    & -2   \\
-3   & 3   
\end{bmatrix}$ is degenerate, and $\text{det} (\mathbf A) = 0$. Meaning, you can't solve a system like this one:


\begin{equation}
\begin{cases}
 2 x_1   - 2 x_2 = 1 \\
-3 x_1   + 3 x_2 = 0 
\end{cases}
\end{equation}

Really though? Let us check. $-3 x_1   + 3 x_2 = 0$, therefore $x_1 = x_2$, and since $ 2 x_1   - 2 x_2 = 1$ we get $ 2 x_1   - 2 x_1 = 1$ and so $ 0 = 1$, which is clearly incorrect.

Conversely - if n vectors $\mathbf v_1$, $\mathbf v_2$, ..., $\mathbf v_n \in \mathbb{R}^n$ are linearly independant - the n-by-n matrix made by concatenating them is going to be full-rank.

# Self-study tasks

1) Solve the following systems:

\begin{equation}
\begin{cases}
-x_1   - 9 x_2 = 3 \\
7 x_1  + 2 x_2 = -3 
\end{cases}
\end{equation}

\begin{equation}
\begin{cases}
 2x_1   - 10 x_2 = 2 \\
-3 x_1  + 5  x_2 = 1 
\end{cases}
\end{equation}

\begin{equation}
\begin{cases}
-  x_1  + 5 x_2 = 9 \\
-2 x_1  - 2 x_2 = 0 
\end{cases}
\end{equation}

\begin{equation}
\begin{cases}
   x_1  + 5  x_2 = 1 \\
-2 x_1  - 10 x_2 = 5 
\end{cases}
\end{equation}


\begin{equation}
\begin{cases}
   x_1  - 5  x_2 + x_3   = 5 \\
-2 x_1  - 10 x_2 + 7 x_3 = 5 
\end{cases}
\end{equation}

2) Find determinant for the following matrices, by hand and in code:

\begin{equation}
\mathbf A =
\begin{bmatrix}
1   & -2 \\
3   & -6 
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf A =
\begin{bmatrix}
1   & 0 \\
5   & 1 
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf A =
\begin{bmatrix}
-1   & 4 \\
-1   & 0 
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf A =
\begin{bmatrix}
-2   & 1 \\
-10   & 0 
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf A =
\begin{bmatrix}
-10   & 1 \\
 10   & 5 
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf A =
\begin{bmatrix}
-3   & 0 \\
 3   & 0 
\end{bmatrix}
\end{equation}

Find norms of the columns of these matrices

3) Provide 3 examples of degenerate 3 by 3 matrices. Show that their determinants are zero.

4) Consider vectors, are they linearly independant?

\begin{equation}
\mathbf v_1 =
\begin{bmatrix}
3       \\
-4    
\end{bmatrix}, \ \ 
\mathbf v_2 =
\begin{bmatrix}
5     \\
1    
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf v_1 =
\begin{bmatrix}
10       \\
-15    
\end{bmatrix}, \ \ 
\mathbf v_2 =
\begin{bmatrix}
-2     \\
3    
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf v_1 =
\begin{bmatrix}
2       \\
5    
\end{bmatrix}, \ \ 
\mathbf v_2 =
\begin{bmatrix}
1     \\
10    
\end{bmatrix}
\end{equation}


\begin{equation}
\mathbf v_1 =
\begin{bmatrix}
2       \\
2       \\
5    
\end{bmatrix}, \ \ 
\mathbf v_2 =
\begin{bmatrix}
1     \\
0     \\
0    
\end{bmatrix}, \ \ 
\mathbf v_3 =
\begin{bmatrix}
-1     \\
2     \\
0    
\end{bmatrix}
\end{equation}


\begin{equation}
\mathbf v_1 =
\begin{bmatrix}
5       \\
2       \\
5    
\end{bmatrix}, \ \ 
\mathbf v_2 =
\begin{bmatrix}
-1     \\
2     \\
3    
\end{bmatrix}, \ \ 
\mathbf v_3 =
\begin{bmatrix}
5     \\
-10     \\
-15    
\end{bmatrix}
\end{equation}


\begin{equation}
\mathbf v_1 =
\begin{bmatrix}
1       \\
2       \\
2    
\end{bmatrix}, \ \ 
\mathbf v_2 =
\begin{bmatrix}
3     \\
0     \\
2    
\end{bmatrix}, \ \ 
\mathbf v_3 =
\begin{bmatrix}
7     \\
2     \\
6    
\end{bmatrix}
\end{equation}